export const GET_ISSUES_REQUESTED = 'GET_ISSUES_REQUESTED';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAILED = 'GET_ISSUES_FAILED';

export const POST_ISSUES_REQUESTED = 'POST_ISSUES';
export const POST_ISSUES_SUCCESS = 'POST_ISSUES_SUCCESS';
export const POST_ISSUES_FAILED = 'POST_ISSUES_FAILED';